---

- name: add nginx repo
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: make sure nginx start on boot
  service:
    name: nginx
    enabled: yes
  notify:
    - restart ntp
